name: Test-Event
on: push #Single workflow events
#on: [push, workflow_dispatch]  #Multiple workflow events
jobs: #Job specification
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Get the code from repo
        uses: actions/checkout@v7
      - name: install nodejs
        uses: actions/setup-node@v7
        with:
          node-version: 24
          package-manager-cache: false
      - name: Install dependencies
        run: npm install
        working-directory: ./02 Starting Project/
      - name: run specific tests
        run: npm test
        working-directory: ./02 Starting Project/
  deploy:
    needs: test #Dependency on test job
    runs-on: ubuntu-latest # Runner environment
    steps: 
      - name: Get the code from repo
        uses: actions/checkout@v7
      - name: install nodejs
        uses: actions/setup-node@v7
        with:
          node-version: 24
          package-manager-cache: false
      - name: Install dependencies
        run: npm install
        working-directory: ./02 Starting Project/
      - name: Deploy
        run: echo "Deploying application"